In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv("mnist_train.csv")

In [3]:
data

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [4]:
X=np.array(data.iloc[:,1:])
X=X/255
X.shape

(60000, 784)

In [5]:
y=np.array(data.iloc[:,:1])
y

array([[5],
       [0],
       [4],
       ...,
       [5],
       [6],
       [8]])

In [6]:
Y=[]
for i in range(y.shape[0]):
    tmp=[0,0,0,0,0,0,0,0,0,0]
    tmp[y[i][0]]=1
    Y.append(tmp)
Y=np.array(Y)
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.05,random_state=42)

In [8]:
print(type(X_train))

<class 'numpy.ndarray'>


In [9]:
class NeuralNetwork:
    def __init__(self,inp,hid,out):
        
       # print(str(inp)+" "+str(hid))
        self.hidden_weights=np.random.randn(inp,hid)
        #print(self.weights_hidden)
        self.output_weights=np.random.randn(hid,out)
        #self.hidden_weights=np.random.randn(inp,hid)
        
        self.hidden_bias=np.zeros(hid)
        self.output_bias=np.zeros(out)
        
        self.learning_rate=0.1
        
    def sigmoid(self,s,deriv=False):
        if(deriv):
            return s*(1-s)
        return 1/(1+np.exp(-s))
    def feed_forward(self,inputs):
        self.hidden_sigma=np.dot(inputs,self.hidden_weights)+self.hidden_bias
        self.hidden_output=self.sigmoid(self.hidden_sigma)
        #print(inputs.shape)
        
        self.output_sigma=np.dot(self.hidden_output,self.output_weights)+self.output_bias
        self.output=self.sigmoid(self.output_sigma)
        return self.output
    def back_propagation(self,inputs,desired_output):
        self.output_error=(desired_output-self.output)
        self.output_delta=self.sigmoid(self.output,deriv=True)*self.output_error
        
        self.hidden_error=np.dot(self.output_weights,self.output_delta.T).T
        self.hidden_delta=self.sigmoid(self.hidden_output,deriv=True)*self.hidden_error
        #print(self.hidden_output.T)
        self.output_weights+=self.learning_rate*np.dot(self.hidden_output.reshape(-1,1),self.output_delta.reshape(1,-1))
        self.hidden_weights+=self.learning_rate*np.dot(inputs.reshape(-1,1),self.hidden_delta.reshape(1,-1))
        
        self.output_bias+=self.learning_rate*(self.output_delta)
        self.hidden_bias=self.learning_rate*(self.hidden_delta)
    def train(self,inputs,desired_output):
        self.feed_forward(inputs)
        self.back_propagation(inputs,desired_output)
        
        

In [10]:
nn=NeuralNetwork(784,350,10)

for i in range(y_train.shape[0]):
    #print(X_train[0][i])
    #print(X_train[i][0])
    nn.train(X_train[i],y_train[i])
 

In [12]:
nn.train(X_train[2],y_train[2])
print(y_train[2])
nn.output

[0 0 0 0 0 0 1 0 0 0]


array([7.88282299e-13, 1.85131402e-13, 4.69018134e-02, 2.14711252e-11,
       3.54787743e-13, 8.26728189e-12, 1.00000000e+00, 7.00224223e-15,
       2.93396512e-12, 1.60589046e-08])